apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: currency-service-api-hpa
  labels:
    app: currency-service-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currency-service-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
