apiVersion: v1
kind: Service
metadata:
  name: currency-service-redis-srv
spec:
  selector:
    app: currency-service-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379