apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service-redis-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service-redis
  template:
    metadata:
      labels:
        app: currency-service-redis
    spec:
      containers:
        - name: currency-service-redis
          image: redis